name: colitas_petshop
description: "Una aplicación móvil en Flutter para reportar y buscar mascotas perdidas en Andahuaylas, Apurímac, como iniciativa de la Veterinaria Colitas Petshop."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos adicionales
  cupertino_icons: ^1.0.5

  # Firebase dependencies
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.8

  # State management
  provider: ^6.1.1

  # Image selection
  image_picker: ^1.0.7

  # Aesthetics
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
