import 'dart:io';
import 'package:flutter/material.dart';
import '../models/app_user.dart';
import '../models/pet.dart';
import '../services/auth_service.dart';
import '../services/firestore_service.dart';
import '../services/storage_service.dart';

class AppState extends ChangeNotifier {
  final AuthService _authService = AuthService();
  final FirestoreService _firestoreService = FirestoreService();
  final StorageService _storageService = StorageService();

  AppUser? _currentUser;
  List<Pet> _pets = [];
  bool _isLoading = false;
  String _filterState = 'Todos'; // 'Todos' | 'Perdido' | 'Encontrado'
  String _searchQuery = '';

  AppUser? get currentUser => _currentUser;
  List<Pet> get pets => _pets;
  bool get isLoading => _isLoading;
  String get filterState => _filterState;
  String get searchQuery => _searchQuery;

  bool get isAuthenticated => _currentUser != null;

  AppState() {
    _init();
  }

  void _init() {
    _isLoading = true;
    notifyListeners();

    // Listen to authentication changes
    _authService.authStateChanges.listen((user) {
      _currentUser = user;
      notifyListeners();
    });

    // Load initial pets list
    fetchPets();
  }

  Future<void> fetchPets() async {
    _isLoading = true;
    notifyListeners();
    try {
      _pets = await _firestoreService.getPets();
    } catch (e) {
      debugPrint("Error fetching pets: $e");
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Filtered list based on current filter state and search query
  List<Pet> get filteredPets {
    return _pets.where((pet) {
      // 1. Filter by status (Perdido/Encontrado)
      if (_filterState != 'Todos' && pet.estado.toLowerCase() != _filterState.toLowerCase()) {
        return false;
      }
      
      // 2. Filter by search query (name or location)
      if (_searchQuery.isNotEmpty) {
        final query = _searchQuery.toLowerCase();
        final matchesName = pet.nombre.toLowerCase().contains(query);
        final matchesLocation = pet.lugar.toLowerCase().contains(query);
        final matchesBreed = pet.raza.toLowerCase().contains(query);
        return matchesName || matchesLocation || matchesBreed;
      }

      return true;
    }).toList();
  }

  void setFilterState(String state) {
    _filterState = state;
    notifyListeners();
  }

  void setSearchQuery(String query) {
    _searchQuery = query;
    notifyListeners();
  }

  // Authentication Actions
  Future<void> signIn(String email, String password) async {
    _isLoading = true;
    notifyListeners();
    try {
      _currentUser = await _authService.signIn(email, password);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> signUp(String nombre, String email, String password) async {
    _isLoading = true;
    notifyListeners();
    try {
      _currentUser = await _authService.signUp(nombre, email, password);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> reloadCurrentUser() async {
    _isLoading = true;
    notifyListeners();
    try {
      _currentUser = await _authService.reloadCurrentUser();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> sendVerificationEmail() async {
    _isLoading = true;
    notifyListeners();
    try {
      await _authService.sendVerificationEmail();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> signOut() async {
    _isLoading = true;
    notifyListeners();
    try {
      await _authService.signOut();
      _currentUser = null;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Pet Actions (CRUD)
  Future<void> createPet({
    required String nombre,
    required String raza,
    required String color,
    required String descripcion,
    required DateTime fechaPerdida,
    required String lugar,
    required String contacto,
    String? recompensa,
    required String estado,
    required File? imageFile,
  }) async {
    if (_currentUser == null) throw Exception("Inicia sesión para reportar una mascota.");
    if (imageFile == null) throw Exception("Es obligatorio subir una fotografía.");

    _isLoading = true;
    notifyListeners();

    try {
      // 1. Upload photo
      final fotoUrl = await _storageService.uploadPetPhoto(imageFile, nombre);

      // 2. Create object
      final pet = Pet(
        id: '', // Will be generated by database
        nombre: nombre,
        raza: raza,
        color: color,
        descripcion: descripcion,
        fechaPerdida: fechaPerdida,
        lugar: lugar,
        contacto: contacto,
        recompensa: recompensa?.isEmpty ?? true ? null : recompensa,
        estado: estado,
        fotoUrl: fotoUrl,
        userId: _currentUser!.id,
      );

      // 3. Save to database
      await _firestoreService.addPet(pet);
      
      // 4. Refresh local list
      await fetchPets();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> updatePetDetails({
    required String petId,
    required String nombre,
    required String raza,
    required String color,
    required String descripcion,
    required DateTime fechaPerdida,
    required String lugar,
    required String contacto,
    String? recompensa,
    required String estado,
    required String existingFotoUrl,
    File? newImageFile,
  }) async {
    if (_currentUser == null) throw Exception("Inicia sesión para editar esta publicación.");

    _isLoading = true;
    notifyListeners();

    try {
      String fotoUrl = existingFotoUrl;
      
      // Upload new image if chosen
      if (newImageFile != null) {
        fotoUrl = await _storageService.uploadPetPhoto(newImageFile, nombre);
      }

      final pet = Pet(
        id: petId,
        nombre: nombre,
        raza: raza,
        color: color,
        descripcion: descripcion,
        fechaPerdida: fechaPerdida,
        lugar: lugar,
        contacto: contacto,
        recompensa: recompensa?.isEmpty ?? true ? null : recompensa,
        estado: estado,
        fotoUrl: fotoUrl,
        userId: _currentUser!.id,
      );

      await _firestoreService.updatePet(pet);
      await fetchPets();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> markAsFound(Pet pet) async {
    if (_currentUser == null || _currentUser!.id != pet.userId) {
      throw Exception("No tienes permisos para modificar esta publicación.");
    }

    _isLoading = true;
    notifyListeners();

    try {
      final updatedPet = pet.copyWith(estado: 'Encontrado');
      await _firestoreService.updatePet(updatedPet);
      await fetchPets();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> deletePetReport(String petId) async {
    if (_currentUser == null) throw Exception("Inicia sesión para eliminar esta publicación.");

    _isLoading = true;
    notifyListeners();

    try {
      await _firestoreService.deletePet(petId);
      await fetchPets();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}
